

services:
  builder:
    build: .
    image: rookie-linux-builder
    container_name: rookie-builder
    # Se recomienda privileged en contenedores que manipulan particiones y montajes ISO (isohybrid, mtools, etc)
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      # Monta la carpeta actual de Windows/Linux dentro del contenedor en /workspace
      - .:/workspace
    environment:
      # Variable para elegir la distribucion. Por defecto: ubuntu
      - ISO_DISTRO=ubuntu
      # - ISO_NAME=custom.iso # Descomentar para forzar un nombre especifico
