# Ubuntu configuration

# Rama de Ubuntu que queremos utilizar
UBUNTU_RELEASE="24.04"

# Tipo de imagen
# desktop = Ubuntu con entorno gráfico
UBUNTU_FLAVOR="desktop"

# Arquitectura del procesador
UBUNTU_ARCH="amd64"

# Servidor oficial de descargas
UBUNTU_MIRROR="https://releases.ubuntu.com"